version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: fintech
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports: ["6379:6379"]
  kafka:
    image: bitnami/kafka:3.6
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports: ["9092:9092"]
  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports: ["16686:16686", "4317:4317", "4318:4318"]
  issuer-gateway:
    build: ../../services/issuer-gateway-py
    environment:
      - LEDGER_URL=http://ledger:8080
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=postings
    ports: ["8081:8080"]
    depends_on: [postgres, kafka, ledger]

  ledger:
    build: ../../services/ledger-py
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@postgres:5432/fintech
    ports: ["8082:8080"]
    depends_on: [postgres]

  rewards:
    build: ../../services/rewards-py
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@postgres:5432/fintech
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=postings
    depends_on: [postgres, kafka]

  risk:
    build: ../../services/risk-py
    ports: ["8084:8080"]
    depends_on: [postgres]

  compliance:
    build: ../../services/compliance-py
    ports: ["8085:8080"]
    depends_on: [postgres]

  recon:
    build: ../../services/recon-py
    ports: ["8086:8080"]
    depends_on: [postgres]

  notifier:
    build: ../../services/notifier-py
    ports: ["8087:8080"]
    depends_on: [postgres]
volumes:
  pgdata:
